before_script:
  - npm install -g bower
  - npm install -g karma
  - npm install -g karma-cli
  - npm install -g babel-cli
  - bower install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - node ./server/controllers/controller.js

addons:
  firefox: latest
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - CXX=g++-4.8
language: node_js
node_js:
  - 5.9.1
services:
  - mysql
before_install:
  - touch serverconfig.js
  - mysql -u root -e 'create database blood;'
after_success:
  - npm run coverage
  - npm run report-coverage
